name: Java CI

on:
  push:
    branches:  [Mmark98-patch-1]
  pull_request:
    branches: [Mmark98-patch-1]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build and publish with Maven
        run: |
            cd  

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2


      - name: Test with Maven
        run: mvn test

      - name: Test with Maven and generate Jacoco report
        run: mvn test jacoco:report

      - name: Run the application
        run: mvn spring-boot:run
