name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3  # Frissítve a legújabb verzióra
        
      - name: Set up JDK 17
        uses: actions/setup-java@v2  # Frissítve a legújabb verzióra
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn clean install
        working-directory: library
